### ISSUE TITLE
Cross-check implementations

### ISSUE THREAD

**Issue by lindnemi** [luap-pik/SyntheticNetworks#18]
In our attempts to reproduce https://core.ac.uk/download/pdf/77050448.pdf we noticed that the statistics of ~500 graphs generated with the SyntheticNetworks.jl were different from the statistics of the graphs used for the paper. Most notably, the statistics for triangles and clustering were off. We didn't look into it further, but as a sanity test it might help to generate ensembles of graphs with identical parameters in both SyntheticNetworks.jl and in the python version (https://github.com/PIK-ICoN/SyntheticNetworks-python) and compare their statistics.

**Comment by acejolanda** [comment]
By generating an ensemble of 1000 networks with the packages SyntheticNetworks.jl and SyntheticNetworks-python.py and then comparing different statistics (e.g. average node degree, assortativity, average shortest path length and global clustering coefficient), a very similar distribution can be observed in both cases:
[example_of_comparison.pdf](https://github.com/PIK-ICoNe/SyntheticNetworks/files/6998829/example_of_comparison.pdf)

More information about the code can be found in this repository:
https://github.com/PIK-ICoNe/SyntheticNetworks_comparison

**Comment by lindnemi** [comment]
Great work, thanks :)
